version: '3.1'

services:
  db:
    image: mysql
    container_name: CrudClientRegistration_Database
    environment:
      MYSQL_ROOT_PASSWORD: syxbruno
    ports:
      - "3306:3306"
    volumes:
      - syxbruno_data:/var/lib/CrudClientRegistration_Database

volumes:
  syxbruno_data: