version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: CrudClientRegistration_Database
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: CrudClientRegistration_Database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: