server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client?createDatabaseIfNotExist=true
    username: root
    password: syxbruno
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
