server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CrudClientRegistration_Database
    username: bruno
    password: '12345'
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  default-produces-media-type: application/json
